OwnOurLand/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import profile_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('account/profile/', profile_view, name='profile'),
    path('cart/', include('shopping_cart.urls', namespace='cart')),
    path('', include('books.urls', namespace='books'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from .views import (
    book_list, 
    book_detail, 
    chapter_detail,
    exercise_detail,
    ebooks
)

app_name = 'books'

urlpatterns = [
    path('', book_list, name='book-list'),
    path('<slug>/', book_detail, name='book-detail'),
    path('<book_slug>/<int:chapter_number>', chapter_detail, name='chapter-detail'),
    path('<book_slug>/<int:chapter_number>/<int:exercise_number>/', exercise_detail, name='exercise-detail'),
    path('ebooks/', ebooks, name='exercise-detail'),
    path('ebook/<int:ebook_id>', ebooks, name='exercise-detail')
]

shopping_cart/urls.py
from django.urls import path
from .views import (
    add_to_cart,
    remove_from_cart,
    order_view,
    checkout
)

app_name = 'shopping_cart'

urlpatterns = [
    path('add-to-cart/<book_slug>/',
         add_to_cart,
         name='add-to-cart'),
    path('remove-from-cart/<book_slug>/',
         remove_from_cart,
         name='remove-from-cart'),
    path('order-summary/', order_view, name='order-summary'),
    path('checkout/', checkout, name='checkout')
]

books/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.shortcuts import redirect, reverse
from django.contrib.auth.models import User



class UserLibrary(models.Model):
    books = models.ManyToManyField('Book', blank=True)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def book_list(self):
        return self.books.all()

    class Meta:
        verbose_name = 'User Library'
        verbose_name_plural = 'User Library'


def post_user_signup_receiver(sender, instance, created, *args, **kwargs):
    if created:
        UserLibrary.objects.get_or_create(user=instance)


post_save.connect(post_user_signup_receiver, sender=settings.AUTH_USER_MODEL)





class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    slug = models.SlugField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Book(models.Model):
    authors = models.ManyToManyField(Author)
    title = models.CharField(max_length=100)
    publication_date = models.DateTimeField()
    isbn = models.CharField(max_length=16)
    slug = models.SlugField()
    cover = models.ImageField()
    price = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book-detail", kwargs={
            'slug': self.slug
            })



class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
            return reverse("books:chapter-detail", kwargs={
            'book_slug': self.book.slug,
            'chapter_number': self.chapter_number
            })



class Exercise(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    exercise_number = models.IntegerField()
    page_number = models.IntegerField()  
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
            return reverse("books:exercise-detail", kwargs={
            'book_slug': self.chapter.book.slug,
            'chapter_number': self.chapter.chapter_number,
            'exercise_number': self.exercise_number
            })

class Solution(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    solution_number = models.IntegerField()
    chapters = models.FileField(upload_to='chapters/')
   

    def __str__(self):
        return f"{self.exercise.title}-{self.pk}"



# ebook model
class Ebook(models.Model):
    title = models.CharField(max_length=200)
    authors = models.CharField(max_length=255)
    isbn = models.CharField(max_length=13)
    pages = models.IntegerField()
    price = models.FloatField()
    image = models.ImageField(upload_to='images/')
    # this will be the download link of the ebook
    ebook = models.FileField(upload_to='ebooks/')



    def __str__(self):
        return self.title



class Comment(models.Model):
    body = models.TextField()
    pub_time = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ebook = models.ForeignKey(Ebook, on_delete=models.CASCADE)


    def pub_date_pretty(self):
        return self.pub_time.strftime('%b %e %Y')

shopping_cart/models.py
from django.conf import settings
from django.db.models import Sum
from django.db import models
from books.models import Book


class OrderItem(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.book.title


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    ref_code = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

    def get_total(self):
        return self.items.all().aggregate(order_total=Sum('book__price'))['order_total']


class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    total_amount = models.FloatField()
    date_paid = models.DateTimeField(auto_now_add=True)
    stipe_charge_id = models.CharField(max_length=100)

    def __str__(self):
        return self.stipe_charge_id

templates/base.html
{% load static %}
<!DOCTYPE HTML>

<html>
	<head>
		<title>OwnOurLand</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" >
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
		  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	</head>

	<body>
	{% include "navbar.html" %}
		<div id="container">
	
  {% include 'messages.html' %}


			<!-- Header -->

			<!-- Main -->
				<section id="banner">
					<h2 style="text-align: center;color:#ffd31d">
   				Own Our Land
  				
					</h2>
					      {% block breadcrumb %}
        					{% endblock breadcrumb %}
					<div class="container" id="book">
					<div class="row justify-content-center">
					  
                      {% block content %}

                        {% endblock %}
					</div>
                     </div> 
					

				</section>

			<!-- Main -->
				<section id="main" class="container">
					<div class="row justify-content-center">
					<section class="col-md-8 box special pt-2" id="blist">
						<header class="major">
							<h2>Nutrition and Conditioning Services
							<br />
							To help you build habits</h2>
						</header>
   
                        
 			<section class="box special features" id="plans">
						<div class="features-row">
						 
							<section>
								<span><img class="img-fluid" src="{%static 'images/mainPic.svg' %}" style="width:40rem;align-content:center"></span>
								<h3>Weight Loss</h3>
								<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
							</section>
							<section>
								<span class=""></span>
								<h3>Lactation</h3>
								<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
							</section>
						</div>
						<div class="features-row">
							<section>
								<span><img src="{% static 'images/root.svg' %}" style="height:6rem;width:6rem;"></span>
								<h3>Astrology</h3>
								<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
							</section>
							<section>
								<span class="img-fluid"><img src="{% static 'images/veg.jpg' %}" class="rounded" alt="info" style="width:20rem"></i></span>
								<h3>Meat 2 Plant</h3>
								<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
							</section>
					</div>
						</div>
					</section>
					
					 		



					
				
					

				</section>

				<!-- herbs -->

				<div class="row mt-4" id="herbs" style="text-align: center;">
				
  					<div class="col">
					  <h3>Capsules</h3>
					  </div>
  					<div class="col">
					  
					   <h3>Teas</h3>
					  </div>
 					 <div class="w-100"></div>
 					 <div class="col">
					   <h3>Drink Mixture</h3>
					  </div>
 					 <div class="col">
					   <h3>Seasonings</h3>
					  </div>
				</div>

			<!-- CTA -->
				<section id="cta" style="text-align: center;">


					<form>
						<div class="row gtr-50 gtr-uniform">


						</div>
					</form>

				</section>

			<!-- Footer -->
				<footer id="footer" style="text-align: center; margin-top:2rem">
					<ul class="icons">
						<li><a href="https://twitter.com/OwnOurLand"><i class="icon brands fa-twitter"></i></a></li>
						<li><a href="https://www.facebook.com/search/top/?q=ja%27brenna%20brown"><i class="icon brands fa-facebook-f"></i></a></li>
						<li><a href="https://www.instagram.com/jabrennab/"><i class="icon brands fa-instagram"></i></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; All rights reserved.</li><li> <a href="https://OwnOurLand.com">Own Our Land</a></li>
						<a href="#banner"><img src="{%static 'images/favicon.png'%}" style="height:4rem;width:4rem"></a>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>
			
			<script>
$(document).ready(function(){
  // Add smooth scrolling to all links
  $("a").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 800, function(){

        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
});
</script>

	</body>
</html>

templates/book_detail.html
{% extends "base.html" %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
		<ol class="breadcrumb" style="text-decoration:none;">
	<li class="breadcrumb-item" aria-current="page">
	<a href="{% url 'books:book-list' %}">Book List</a>
	</li>
	<li class="breadcrumb-item active" aria-current="page">
	{{ book.title }}
	</li>
	</ol>
	</nav>
{% endblock breadcrumb %}

{% block content %}
	
	<div class="row justify-content-md-center" style="marign-left:auto;margin-right:auto">
	<main class="col-md-8">
		<h1 style="color: #C0C0C0">OUL Digital Ebooks</h1>
	{% include 'book_snippet.html' with book=book %}
</main>

		<aside class="col-md-8">								
						  
						   
  						 <div class="card">
						   <div class="card-header" style="color:#333">
							Chapters
						   </div>
  								
 						<ul class="list-group list-group-flush">
						  {% for chapter in book.chapter_set.all %}	
  							<li class="list-group-item">
							  <a href="{{ chapter.get_absolute_url }}">{{ chapter.chapter_number }}. {{ chapter.title }}</a>
							  </li>
								  </ul>
			   {% endfor %}			
			   </div>				
					</aside>
	</div>
      
                       

{% endblock content %}

templates/book_list.html
{% extends "base.html" %}
{% load static %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<a href="#book" class="breadcrumb-item active" aria-current="page" style="margin-right:auto;margin-left:auto;">Book List</a>
</ol>

</nav>
{% endblock breadcrumb %}

                     {% block content %}
				      
   

          
                        {% for book in queryset %}
                           
                               <div class="row mt-2">
                              <main class="col-xs-12 col-sm-12 col-md-4" style="padding:1rem">
                        <div class="card h-100" style="width: 18rem;background-color:#ffcd3c;">
                           <img class="card-img-top" src="{{ book.cover.url }}" alt="Card image cap">
                           <div class="card-body">
                            <h5 class="card-title">{{ book.title }}</h5>
                            <p class="card-text">
                            {% for author in book.authors.all %}
                            <span> {{author}}</span>
                           {% if book.authors.count > 1 %} | {% endif %}
                            {% endfor %}
                            
                            </p>

                          <a href="{{ book.get_absolute_url }}" class="btn btn-primary">{{ book }}</a>
                            </div>
                              </div>
                              </main>
            </div>
         
                        {% endfor %}
                    
                       

{% endblock content %}

		
	

templates/book_snippet.html
<div class="card">
    <div class="card-header">{{ book.title }}</div>
    <img src="{{ book.cover.url }}" class="card-img-top" alt="...">
    <div class="card-body">
        <p class="card-text">Published: {{ book.publication_date }}</p>
    </div>
    {% if book_status != 'owned' %}
        <div class="card-footer">
        {% if book_status == 'in_cart' %}
        <a href="{% url 'cart:remove-from-cart' book.slug %}" class="btn btn-default btn-block">
            Remove from cart
        </a>
        {% else %}
        <a href="{% url 'cart:add-to-cart' book.slug %}" class="btn btn-warning btn-block">
            Add to cart
        </a>
        {% endif %}
        </div>
    {% endif %}
</div>       

templates/chapter_detail.html
  {% extends "base.html" %}
{% load static %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item" aria-current="page">
    <a href="{% url 'books:book-list' %}">Book List</a>
</li>
<li class="breadcrumb-item" aria-current="page">
   <a href="{{ chapter.book.get_absolute_url }}">
    {{ chapter.book.title }}
    </a>
</li>
<li class="breadcrumb-item active" aria-current="page">
    {{ chapter }}
</li>
</ol>
</nav>
{% endblock breadcrumb %}

{% block content %}

<div class="row justify-content-md-center mt-4">


	<main class="col-md-8">
{% include 'book_snippet.html' with book=chapter.book %}
		       
</main>


    <aside class="col-md-8">
    <div class="card">
        <div class="card-header" style="color:#80bdab">
            Chapters
        </div>
        <ul class="list-group list-group-flush">
            {% for exercise in chapter.exercise_set.all %}
            <li class="list-group-item">
            <a href="{{ exercise.get_absolute_url }}">
                {{ exercise.exercise_number }}. {{ exercise.title }}
            </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    
    </aside>
</div>

{% endblock content %}

templates/exercise_detail.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
	<li class="breadcrumb-item" aria-current="page">
	<a href="{% url 'books:book-list' %}">Book List</a>

	</li>
	<li class="breadcrumb-item" aria-current="page">
		<a href="{{ exercise.chapter.book.get_absolute_url }}"> 
		{{ exercise.chapter.book.title }}
		 </a>
	</li>
	<li class="breadcrumb-item" aria-current="page">
				<a href="{{ exercise.chapter.get_absolute_url }}"> 
				{{ exercise.chapter.title }} 
				</a>
	</li>
		<li class="breadcrumb-item active" aria-current="page">
		 {{ exercise.title }} 
	</li>
    </ol>
    </nav>
{% endblock breadcrumb %}

{% block content %}

<div class="row justify-content-md-center mt-4">
    <main class="col-md-8">
  {% include "book_snippet.html" with book=exercise.chapter.book %}
  
 </main>
    <aside class="col-md-8">
    <div class="card">
        <div class="card-header">
            Book
        </div>

            {% if exercise.chapter.book in request.user.userlibrary.book_list %}
<!--- book_status == 'owned' -->
            {% for solution in exercise.solution_set.all %}



            <div class="accordion" id="toggle-{{ solution.solution_number }}">
                <div class="card justify-content-md-center">
                    <div class="card-header" id="heading-{{ solution.solution_number }}">
                    <h2 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse-{{ solution.solution_number }}" aria-expanded="true" aria-controls="collapse-{{ solution.solution_number }}">
                        Chapter 
                        </button>
                    </h2>
                    </div>


                    <div id="collapse-{{ solution.solution_number }}" class="collapse" aria-labelledby="heading-{{ solution.solution_number }}" data-parent="#toggle-{{ solution.solution_number }}">
                     <div class="card">
                    <div class="card-body">
                        <p><a class="btn btn-success" href="{{ solution.chapters.url }}">{{ solution.exercise }}</a></p> <!-- Ebook.ebook.url -->
                    </div>
                    </div>            
                    </div>
                      
                </div>
            </div>



            {% endfor %}

            {% else %}
        <div class="text-center"> 
            <a href="#">Purchase this book</a> to have access to the solutions
            </h4>
            <img class="justify-content-md-center" src="{%static 'images/land.svg' %}" />
            {% endif %}
        </div>
    </div>
    
    </aside>
	 
</div>

{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load cart_template_tags %}
{% load static %}


<nav  class="navbar navbar-expand-md navbar-light bg-faded" style="background-color: #96bb7c;">

  <a class="navbar-brand mt-auto" href="{% url 'books:book-list' %}"><img src="{%static 'images/favicon.png'%}" style="height:3.2rem;width:3.8rem;"></a>
  
    <div class="collapse navbar-collapse" id="navbarCollapse">

    <ul class="navbar-nav">

        <li class="nav-item">
        <a class="nav-link mr-auto" href="#plans">Healing Consultation</a>
        </li>
      <li class="nav-item">
        <a class="nav-link" href="#herbs">Herbs</a>
    </li>
    {% if request.user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:order-summary' %}">
        {{ request.user|cart_item_count }}
        <i class="fa fa-shopping-cart"></i>
        </a>
    </li>
    <li class="nav-item" style="text-align: right;">
     <a class="nav-link" href="{% url 'profile' %}">Account</a>
     </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
    </li>
    
     
    {% endif %}
    </ul>
  
    <ul class="navbar-nav ml-auto mb-auto">
      <li class="nav-item">
        <a href="https://www.twitter.com/ownourland" class="nav-link waves-effect waves-light">
          <i class="icon brands fa-twitter"></i>
        </a>
      </li>
      <li class="nav-item">
  
        <a href="https://instagram.com/jabrennab" class="nav-link waves-effect waves-light">
          <i class="icon brands fa-instagram"></i>
        </a>
      
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link"
          aria-haspopup="true" aria-expanded="false">
          <i class="icon brands fa-facebook-f"></i>
        </a>

      </li>
    </ul>
</div>
</nav>



<!--
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded" id="nav">

<a class="navbar-brand" href="{% url 'books:book-list' %}" style="text-decoration:none">OwnOurLand</a>

<div class="collapse navbar-collapse" id="navbarsExample09">

    <ul class="navbar-nav mr-auto">

        <li class="nav-item">
        <a class="nav-link" href="#plans">Healing Consultation</a>
    </li>
      <li class="nav-item">
        <a class="nav-link" href="#herbs">Herbs</a>
    </li>
    {% if request.user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:order-summary' %}">
        {{ request.user|cart_item_count }}
        <i class="fas fa-shopping-cart"></i>
        </a>
    </li>
    <li class="nav-item" style="text-align: right;">
     <a class="nav-link" href="{% url 'profile' %}">Account</a>
     </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
    </li>
    
     
    {% endif %}
    </ul>
  
</div>
</nav>

-->

		
					
					
                   
			

templates/order_summary.html
{% extends "base.html" %}

{% block content %}

<h1>Order Summary</h1>
<hr />

<table class="table table-hover table-bordered text-center">
    <tr class="text-center">
        <th>no.</th>
        <th>Title</th>
        <th>Price</th>
    </tr>
    {% for item in order.items.all %}
    <tr style="background-color:#fff">
        <td>{{ forloop.counter }}</td>
        <td>{{ item.book.title }}
        <span>
        <a href="{% url 'cart:remove-from-cart' item.book.slug %}" class="text-danger">
            <i class="fas fa-trash"></i>
        </a>
        </span>
        </td>
        <td>${{ item.book.price }}</td>
    </tr>
    {% empty %}
    <tr style="background-color:#fff">
    <td colspan="3">
        There are no items in your cart
    </td>
    </tr>
    {% endfor %}
    {% if order.get_total %}
    <tr style="background-color:#fff!important">
    <td colspan="2">
        <strong class="pull-right">Order total: </strong>
    </td>
    <td colspan="1">
        <strong>${{ order.get_total }}</strong>
    </td>
    </tr>
    {% endif %}
    <tr style="background-color:#fff">
        <td colspan="3">
            <a href="{% url 'books:book-list' %}" class="btn btn-warning pull-left">
            {% if order %}
                Continue shopping
            {% else %}
                Add items to your cart
            {% endif %}
            </a>
        </td>
    </tr>
    {% if order.get_total %}
    <tr>
        <td colspan="3">
            <a href="{% url 'cart:checkout' %}" class="btn btn-primary pull-left">
                Checkout
            </a>
        </td>
    </tr>
    {% endif %}
</table>

{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}

<h1 style="color:#fff">Previous orders</h1>
<hr />

<table class="table table-hover table-bordered text-center">
    <tr class="text-center">
        <th>no.</th>
        <th>Reference code</th>
        <th>Amount</th>
        <th>Date</th>
    </tr>
    {% for order in orders %}
    <tr style="background-color:#fff">
        <td>{{ forloop.counter }}</td>
        <td>{{ order.ref_code }}</td>
        <td>${{ order.get_total }}</td>
        <td>{{ order.payment_set.first.date_paid }}</td>

    </tr>
    {% empty %}
    <tr>
    <td colspan="4">
        You have not purchased anything
    </td>
    </tr>
    {% endfor %}
</table>

{% endblock content %}